// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5LOfH__N7Lv5kbFbbAS0SZTlht2r5f4c',
    appId: '1:1079909316054:web:a34174031fb5fcb76a6077',
    messagingSenderId: '1079909316054',
    projectId: 'scouting-app-865',
    authDomain: 'scouting-app-865.firebaseapp.com',
    storageBucket: 'scouting-app-865.appspot.com',
    measurementId: 'G-N3BFGVZNNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALG8g3I5LRiYeOYy_9i49f4qnNLfhxwps',
    appId: '1:1079909316054:android:f243073ee20cee816a6077',
    messagingSenderId: '1079909316054',
    projectId: 'scouting-app-865',
    storageBucket: 'scouting-app-865.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlVC5ozs1Nh9SwTwRw_fnWhTdCCyHdImc',
    appId: '1:1079909316054:ios:f4d7f848fee3b8956a6077',
    messagingSenderId: '1079909316054',
    projectId: 'scouting-app-865',
    storageBucket: 'scouting-app-865.appspot.com',
    iosClientId: '1079909316054-s21b89ivruepbnfg2ih22rfm81q7u1qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoutingApp865',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5LOfH__N7Lv5kbFbbAS0SZTlht2r5f4c',
    appId: '1:1079909316054:web:b4f54cb22559faaf6a6077',
    messagingSenderId: '1079909316054',
    projectId: 'scouting-app-865',
    authDomain: 'scouting-app-865.firebaseapp.com',
    storageBucket: 'scouting-app-865.appspot.com',
    measurementId: 'G-WYSWEF6BPT',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC5LOfH__N7Lv5kbFbbAS0SZTlht2r5f4c',
    appId: '1:1079909316054:web:ecfb08bf1bc1b3796a6077',
    messagingSenderId: '1079909316054',
    projectId: 'scouting-app-865',
    authDomain: 'scouting-app-865.firebaseapp.com',
    storageBucket: 'scouting-app-865.appspot.com',
    measurementId: 'G-11NB1H4FC0',
  );
}
